Sprint 2
AlexPilinni/middle.messenger.praktikum.yandex pull request #2
Opened 2022-08-05 22:51 UTC by AlexPilinni

2022-08-09 11:03 UTC, podlovchenko requested changes
Привет, в целом все хорошо, есть несколько замечаний)

1. Нет ссылки на фигму в ридми
2. Не выполнено задание с валидацией данных (не хватает валидации некоторых полей на страницах, валидация должна быть по событиями focus/blur)
<img width="916" alt="Снимок экрана 2022-08-09 в 13 52 47" src="https://user-images.githubusercontent.com/22602747/183632357-cfc7b07c-685b-4b80-b9c7-cde0c0546064.png">
3. Стоит привести в порядок проект, убрать закомментированный код, лишние строки, проверить отступы

Жду правок)

2022-08-09 11:03 UTC, podlovchenko commented on package.json
> +    "@parcel/transformer-image": "^2.0.0-rc.0",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-09 11:03 UTC, podlovchenko commented on package.json
> +    "path": "0.12.7",
Это не dev зависимость, path и express необходимы для работы приложения, а в dev зависимостях указыется, то что необходимо для локальной разработки и сборки

2022-08-09 11:03 UTC, podlovchenko commented on src/components/button/button.ts
> +  constructor(propsObj: ButtonProps) {
Обычно именуется просто props

2022-08-09 11:03 UTC, podlovchenko commented on src/components/card/card.ts
> +  users: Array<{id: string, name: string, time: string, message: string, counter: string}>
Лучше вынести определение типа User отдельно, так можно будет его переиспользовать и будет проще читать код

2022-08-09 11:03 UTC, podlovchenko commented on src/components/link-list/link-list.scss
> +
Лишние строки

2022-08-09 11:03 UTC, podlovchenko commented on src/components/link-list/link-list.ts
> +	}
Что-то форматирование поехало

2022-08-09 11:03 UTC, podlovchenko commented on src/core/block.ts
> +export class Block<T> {
То что здесь класс Block определен как дженерик никак не используется, нужно определить тип для props как` T`

```suggestion
export class Block<T extends {
  events?: Events;
  children?: Children;
}> {
  props: T;
```

2022-08-09 11:03 UTC, podlovchenko commented on src/core/block.ts
> +  // }
Закомментированный код не стоит оставлять в проекте

2022-08-09 11:03 UTC, podlovchenko commented on src/core/block.ts
> +  _registerEvents(eventBus: EventBus) {
Для приватных методов не хватает модификаторов private или protected, если их можно переопределить в дочернем классе

2022-08-09 11:03 UTC, podlovchenko commented on src/services/http-service.ts
> +	timeout: number;
Должны быть необязательными

2022-08-10 08:44 UTC, AlexPilinni commented
Спасибо за замечания, все по делу!

2022-08-10 10:02 UTC, AlexPilinni commented
с фиксацией версий, упали тесты:S

2022-08-10 13:26 UTC, podlovchenko requested changes
Есть конфликт версий у пакетов stylelint
Попробуй указать 
"stylelint": "14.9.1"
и обновить package-lock.json

2022-08-10 13:26 UTC, podlovchenko commented on src/core/block.ts
> +export class Block {
Лучше было бы оставить Block дженериком

Пример использования:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-08-10 15:27 UTC, AlexPilinni commented on src/core/block.ts
> +export class Block {
> Есть конфликт версий у пакетов stylelint Попробуй указать "stylelint": "14.9.1" и обновить package-lock.json

не решило проблему

2022-08-11 08:45 UTC, podlovchenko approved these changes
Работу принимаю 👍

2022-08-12 05:05 UTC, merged